export class AuthUser {
    constructor(public id: string,
                public name: string,
                public lastname: string,
                public photo: string,
                public verified: string,
                private verification_token: string,
                public admin: string,
                public adress: string,
                public address_complement: string,
                public address_latitude: number,
                public address_longitude: number,
                public dial_code: string,
                public phone: string,
                public email: string,
                public birthday: string,
                public birth_place: string,
                public postal_code: string,
                public city: string,
                public country: string,
                public gender: string,
                public civility: string,
                public about: string,
                private identity_type: string,
                private identity_nbr: string,
                private identity_place: string,
                private identity_image: string,
                public currency,
                public twitter: string,
                public linkedin: string,
                public youtube: string,
                public nbr_rental: number,
                private taxpayers_number: string,
                public agency: any,
                private professionel_id_card: string,
                private seat: string,
                private date_issue: string,
                private date_end: string,
                private phone_company: string,
                private email_company: string,
                public agent: string,
                public status: string,
                public types: string,
                public email_verified_at: string,
                public created_at: string,
                public updated_at: string,
                public deleted_at: string,

                /*
                    Appends
                 */

                public full_name: string,
                public full_name_abr: string,
                public created_at_human: string,
                public has_photo: boolean,
                public age: number,
                public day_of_birth: number,
                public birth_month: number,
                public birth_year: number,
                public nbr_products: number,
                public is_agent: boolean,
                public completed: boolean) {

    }
}
